//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnglishResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.ressources.EnglishResource", typeof(EnglishResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup job has not been created.
        /// </summary>
        internal static string backupcreatedsuccessfullytext {
            get {
                return ResourceManager.GetString("backupcreatedsuccessfullytext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the destination directory:.
        /// </summary>
        internal static string enterdestinationtext {
            get {
                return ResourceManager.GetString("enterdestinationtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the backup job:.
        /// </summary>
        internal static string enternametext {
            get {
                return ResourceManager.GetString("enternametext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the source directory:.
        /// </summary>
        internal static string entersourcetext {
            get {
                return ResourceManager.GetString("entersourcetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t create more than 5 backup jobs.
        /// </summary>
        internal static string morethan5createdtext {
            get {
                return ResourceManager.GetString("morethan5createdtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no backup job to delete!.
        /// </summary>
        internal static string nobackuptodelete {
            get {
                return ResourceManager.GetString("nobackuptodelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no backup job to edit!.
        /// </summary>
        internal static string nobackuptoedit {
            get {
                return ResourceManager.GetString("nobackuptoedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a backup job.
        /// </summary>
        internal static string option1 {
            get {
                return ResourceManager.GetString("option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a backup job.
        /// </summary>
        internal static string option2 {
            get {
                return ResourceManager.GetString("option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a backup job.
        /// </summary>
        internal static string option3 {
            get {
                return ResourceManager.GetString("option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a backup job.
        /// </summary>
        internal static string option4 {
            get {
                return ResourceManager.GetString("option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all backup jobs.
        /// </summary>
        internal static string option5 {
            get {
                return ResourceManager.GetString("option5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the screen.
        /// </summary>
        internal static string option6 {
            get {
                return ResourceManager.GetString("option6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string option7 {
            get {
                return ResourceManager.GetString("option7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string option8 {
            get {
                return ResourceManager.GetString("option8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an [green]option[/]?.
        /// </summary>
        internal static string optiontext {
            get {
                return ResourceManager.GetString("optiontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a [green]backup [/]type you want to create:?.
        /// </summary>
        internal static string selectbacukptypetext {
            get {
                return ResourceManager.GetString("selectbacukptypetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number.
        /// </summary>
        internal static string validnumber {
            get {
                return ResourceManager.GetString("validnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do you want to save the logs as XML or JSON ?.
        /// </summary>
        internal static string xmlorjson {
            get {
                return ResourceManager.GetString("xmlorjson", resourceCulture);
            }
        }
    }
}
