//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrenchResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrenchResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.ressources.FrenchResource", typeof(FrenchResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous avez créer le backup avec succés.
        /// </summary>
        internal static string backupcreatedsuccessfullytext {
            get {
                return ResourceManager.GetString("backupcreatedsuccessfullytext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer la déstination.
        /// </summary>
        internal static string enterdestinationtext {
            get {
                return ResourceManager.GetString("enterdestinationtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer le non du backup job:.
        /// </summary>
        internal static string enternametext {
            get {
                return ResourceManager.GetString("enternametext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer la source.
        /// </summary>
        internal static string entersourcetext {
            get {
                return ResourceManager.GetString("entersourcetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous pouvez créer juste 5 backup jobs.
        /// </summary>
        internal static string morethan5createdtext {
            get {
                return ResourceManager.GetString("morethan5createdtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n y a pas de backup job pour supprimer.
        /// </summary>
        internal static string nobackuptodelete {
            get {
                return ResourceManager.GetString("nobackuptodelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n y a pas de backup job pour modifer!.
        /// </summary>
        internal static string nobackuptoedit {
            get {
                return ResourceManager.GetString("nobackuptoedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un backup job.
        /// </summary>
        internal static string option1 {
            get {
                return ResourceManager.GetString("option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exécuter un backup job.
        /// </summary>
        internal static string option2 {
            get {
                return ResourceManager.GetString("option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer un backup job.
        /// </summary>
        internal static string option3 {
            get {
                return ResourceManager.GetString("option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer un backup job.
        /// </summary>
        internal static string option4 {
            get {
                return ResourceManager.GetString("option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listes de tous les backup jobs.
        /// </summary>
        internal static string option5 {
            get {
                return ResourceManager.GetString("option5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the screen.
        /// </summary>
        internal static string option6 {
            get {
                return ResourceManager.GetString("option6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer la langue.
        /// </summary>
        internal static string option7 {
            get {
                return ResourceManager.GetString("option7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortir.
        /// </summary>
        internal static string option8 {
            get {
                return ResourceManager.GetString("option8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez selectionner une [green]option[/]?.
        /// </summary>
        internal static string optiontext {
            get {
                return ResourceManager.GetString("optiontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner le  [green]type  du backup[/] que voulez céer:?.
        /// </summary>
        internal static string selectbacukptypetext {
            get {
                return ResourceManager.GetString("selectbacukptypetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer un nombre valide.
        /// </summary>
        internal static string validnumber {
            get {
                return ResourceManager.GetString("validnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous voullez sauvegarder les logs en format JSON ou XML ?.
        /// </summary>
        internal static string xmlorjson {
            get {
                return ResourceManager.GetString("xmlorjson", resourceCulture);
            }
        }
    }
}
